apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels: 
    role: frontend
    env: demo

spec:
  replicas: 1
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels: 
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec: 
      imagePullSecrets:
      - name: hostel-frontend
      containers:
      - name: frontend
        image: prithvirajawatade/hostel-frontend:latest
        imagePullPolicy: Always
        env:
          - name: REACT_APP_BACKEND_URL
            value: "http://backend.businesskafundaa.com/api/tasks"
        ports:
        - containerPort: 5173