#!/bin/sh
echo "Running ESLint and Prettier..."

echo "Checking frontend folder..."
cd frontend 
npm run format     
cd ..

echo "Checking backend folder..."
cd backend     
npm run format     
cd ..

echo "Linting and formatting completed."