name: Build and Deploy

on:
  push:
    branches:
      - main  # Adjust branch name if needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: nav to backend
        run: cd backend

      - name: Build Docker image
        run: docker build -t prithvirajawatade/backend:latest .

      - name: Push Docker image to Docker Hub
        run: docker push prithvirajawatade/backend:latest

      # - name: Update Kubernetes Deployment
      #   run: kubectl set image deployment/your-deployment-name container-name=yourusername/yourimage:latest
      #   env:
      #     KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
