name: CI

on:
  pull:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Nav to frontend repo
        run: cd backend

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test -- --coverage

      - name: Build
        run: npm run build

      - name: Check if previous steps failed
        run: exit $(jobs -p | xargs -I{} bash -c 'if [ "$(jobs -l {} | grep -o "failed")" = "failed" ]; then exit 1; fi')

      - name: Push changes
        if: success()
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}